---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: installed
      tags:
        - molecule-idempotence-notest
    - name: import icinga2 repo key
      command: "rpm --import https://packages.icinga.com/icinga.key"
      tags:
        - molecule-idempotence-notest
    - name: install icinga2 repo
      command: "yum install https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm -y"
      tags:
        - molecule-idempotence-notest
  collections:
    - t_systems_mms.ansible_collection_icinga
  roles:
    - icinga_agent
  vars:
    icinga_agent_endpoints:
      - name: "icinga2-master1.localdomain"
        host: "192.154.44.101"
      - name: "icinga2-satellite1.localdomain"
        host: "192.154.44.107"
    icinga_agent_zones:
      - name: "master"
        endpoints:
          - "icinga2-master1.localdomain"
      - name: "satellite"
        endpoints:
          - "icinga2-satellite1.localdomain"
        parent: "master"
  post_tasks:
    - name: verify that icinga2.conf exists
      file:
        path: /etc/icinga2/icinga2.conf
        state: file
      register: result_icinga2_conf

    - name: validate icinga2.conf results
      assert:
        that:
          - "result_icinga2_conf.state == 'file'"
          - "result_icinga2_conf.mode == '0640'"
          - "result_icinga2_conf.changed == true"

    - name: verify that constants.conf exists
      file:
        path: /etc/icinga2/constants.conf
        state: file
      register: result_constants_conf

    - name: validate constants.conf results
      assert:
        that:
          - "result_constants_conf.state == 'file'"
          - "result_constants_conf.mode == '0640'"
          - "result_constants_conf.changed == true"

    - name: verify that zones.conf exists
      file:
        path: /etc/icinga2/zones.conf
        state: file
      register: result_zones_conf

    - name: validate zones.conf results
      assert:
        that:
          - "result_zones_conf.state == 'file'"
          - "result_zones_conf.mode == '0640'"
          - "result_zones_conf.changed == true"

    - name: verify that api.conf exists
      file:
        path: /etc/icinga2/features-available/api.conf
        state: file
      register: result_api_conf

    - name: validate api.conf results
      assert:
        that:
          - "result_api_conf.state == 'file'"
          - "result_api_conf.mode == '0640'"
          - "result_api_conf.changed == true"

    - name: verify that icinga2 package is installed
      command: "rpm -q icinga2"
      register: redhat_package_check
      when: ansible_facts['os_family'] == "RedHat"

    - name: verify that icinga2 package is installed
      command: "dpkg-query -l icinga2"
      register: debian_package_check
      when: ansible_facts['os_family'] == "Debian"

    - name: validate that package icinga2 is installed
      assert:
        that:
          - "redhat_package_check.state == 'installed'"
      when: ansible_facts['os_family'] == "RedHat"

    - name: validate that package icinga2 is installed
      assert:
        that:
          - "debian_package_check.state == 'installed'"
      when: ansible_facts['os_family'] == "Debian"
