---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: installed
    - name: import icinga2 repo key
      command: "rpm --import https://packages.icinga.com/icinga.key"
    - name: install icinga2 repo
      command: "yum install https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm -y"
  collections:
    - t_systems_mms.ansible_collection_icinga
  roles:
    - icinga_agent
  vars:
    icinga_agent_endpoints:
      - name: "icinga2-master1.localdomain"
        host: "192.154.44.101"
      - name: "icinga2-satellite1.localdomain"
        host: "192.154.44.107"
    icinga_agent_zones:
      - name: "master"
        endpoints:
          - "icinga2-master1.localdomain"
      - name: "satellite"
        endpoints:
          - "icinga2-satellite1.localdomain"
        parent: "master"
