---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    command: "/usr/sbin/init"
  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  - name: debian10
    image: "geerlingguy/docker-debian10-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
