---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: solita/centos-systemd:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
