---
- name: Converge
  hosts: all
  collections:
    - t_systems_mms.ansible_collection_icinga
  pre_tasks:

    - name: set name of installation package based on distro
      set_fact:
        icinga_install_plugins:
          - nagios-plugins-all
      when:
        - ansible_os_family == 'RedHat'
        - ansible_facts.distribution_major_version | int is version('8', '<')

    - name: set name of installation package based on distro
      set_fact:
        icinga_install_plugins:
          - monitoring-plugins
      when: ansible_os_family == 'Debian'

  roles:
    - icinga_plugins
