---
icinga2_plugins_basedir:
  Debian: /usr/lib/nagios
  RedHat: /usr/lib64/nagios

icinga2_plugins_pluginsdir: "{{ icinga2_plugins_basedir[ansible_os_family] }}/plugins"

icinga2_user:
  Debian: nagios
  RedHat: icinga
icinga2_group:
  Debian: nagios
  RedHat: icinga
