---
name: ansible-test

on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ansible-sanity-tests:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          # It's important that Sanity is tested against all stable-X.Y branches
          # Testing against `devel` may fail as new tests are added.
          - stable-2.9
          - stable-2.10
          - stable-2.11
    runs-on: ubuntu-latest
    steps:
      # ansible-test requires the collection to be in a directory in the form
      # .../ansible_collections/NAMESPACE/COLLECTION_NAME/

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/t_systems_mms/ansible_collection_icinga

      - name: Set up Python ${{ matrix.ansible }}
        uses: actions/setup-python@v2
        with:
          # it is just required to run that once as "ansible-test sanity" in the docker image
          # will run on all python versions it supports.
          python-version: 3.8

      # Install the head of the given branch (devel, stable-2.10)
      - name: Install ansible-base (${{ matrix.ansible }})
        run: python -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      # run ansible-test sanity inside of Docker.
      # The docker container has all the pinned dependencies that are required.
      # Explicity specify the version of Python we want to test
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: ./ansible_collections/t_systems_mms/ansible_collection_icinga

  linting:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/t_systems_mms/ansible_collection_icinga

      - name: Run Linting - icinga_agent
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible_collections/t_systems_mms/ansible_collection_icinga/roles/icinga_agent
          args: "-c ansible_collections/t_systems_mms/ansible_collection_icinga/.ansible-lint"

      - name: Run Linting - icinga_plugins
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible_collections/t_systems_mms/ansible_collection_icinga/roles/icinga_plugins
          args: "-c ansible_collections/t_systems_mms/ansible_collection_icinga/.ansible-lint"

  molecule:
      name: Molecule
      runs-on: ubuntu-latest
      strategy:
        matrix:
          distro:
            - centos7

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            path: ansible_collections/t_systems_mms/ansible_collection_icinga

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
          working-directory: ansible_collections/t_systems_mms/ansible_collection_icinga

        - name: Test with molecule
          run: molecule test
          working-directory: ansible_collections/t_systems_mms/ansible_collection_icinga/roles/icinga_agent
          env:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_DISTRO: ${{ matrix.distro }}
