---
name: Molecule Test
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/t_systems_mms/ansible_collection_icinga

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test with molecule
        run: |
          molecule test
